name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
               echo "Hello World!"
               echo "Agora é a segunda linha"
               ls -l arquivo123
               export var='teste'
               echo "var: $var"
      - name: Print goodbye
        run: | 
               echo "Done - bye!"
               echo "var: $var"
               echo "Será que deu certo? rs"
               [ -f 'arquivo123' ] && { echo "Deu true" ; ls -l arquivo123 ; }
               bash --version
