name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
               echo "Hello World!"
               echo "Agora é a segunda linha"
               if [[ -f 'arquivo123' ]]; then
                 echo "Arquivo123 existe."
               else
                 echo "Arquivo123 não existe."
                 touch Arquivo123 && { echo "Arquivo criado com sucesso." ; }
               fi
               var='Arquivo123'
               echo "var: $var"
      - name: Print goodbye
        run: | 
               echo "Done - bye!"
               echo "Como variaveis não navegam entre os runs de um mesmo step de job, vou fazer de outro jeito rs"
               echo "var: ${var}"
               if [[ -z "${var}" ]]; then
                 echo "Variavel var está vazia. Ajustando..."
                 sleep 3
                 var='Arquivo123'
                 echo "Resolvido."
                 echo '-------'
               fi
               echo "Será que deu certo? rs"
               [[ -f "${var}" ]] && { echo "Deu true" ; ls -l "${var}" ; exit 0 ; }
               bash --version
